services:
  web:
    image: httpd:latest
    expose:
      - "80"
    volumes:
      - ./codi/starship-sorades-13k:/usr/local/apache2/htdocs
    networks:
      - xPj9f4a87

  sDc: # Distribuidor de carga
    image: nginx:latest
    container_name: cNginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "80:8000"
    networks:
      - xPj9f4a87

networks:
  xPj9f4a87:
    name: pj9f4a87
    driver: bridge
